name: wisata_ticketing
description: "The ticketing app for a holiday venue"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.1.4
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  timer_count_down: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true